package com.dh.DentalClinic.service.impl;

import com.dh.DentalClinic.dto.AddressDTO;
import com.dh.DentalClinic.dto.PatientDTO;
import com.dh.DentalClinic.entity.Address;
import com.dh.DentalClinic.entity.Patient;
import com.dh.DentalClinic.exception.ResourceNotFoundException;
import com.dh.DentalClinic.repository.IAppointmentRepository;
import com.dh.DentalClinic.repository.IPatientRepository;
import com.dh.DentalClinic.service.IPatientService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

@Service
public class PatientService implements IPatientService {

    private final IPatientRepository patientRepository;
    private final IAppointmentRepository appointmentRepository;

    @Autowired
    public PatientService(IPatientRepository patientRepository, IAppointmentRepository appointmentRepository) {
        this.patientRepository = patientRepository;
        this.appointmentRepository = appointmentRepository;
    }

    @Override
    @Transactional
    public PatientDTO save(PatientDTO dto) {
        return toDTO(patientRepository.save(toEntity(dto)));
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<PatientDTO> findById(Long id) {
        return patientRepository.findById(id).map(this::toDTO);
    }

    @Override
    @Transactional
    public PatientDTO update(PatientDTO dto) {
        if (dto.id() == null) {
            throw new IllegalArgumentException("El id del paciente es requerido para actualizar");
        }
        Patient existing = patientRepository.findById(dto.id())
                .orElseThrow(() -> new ResourceNotFoundException("No se encontró el paciente con id: " + dto.id()));

        // Merge sobre la entidad managed para no pisar campos no enviados
        existing.setName(dto.name());
        existing.setLastName(dto.lastName());
        existing.setEmail(dto.email());
        existing.setCardIdentity(dto.cardIdentity());
        existing.setAdmissionDate(dto.admissionDate());
        if (dto.address() != null) {
            Address address = existing.getAddress() != null ? existing.getAddress() : new Address();
            // Never overwrite address.id from the DTO — it is DB-managed.
            // If existing.getAddress() was null we have a new transient Address; setting a
            // foreign id would make JPA cascade-merge it as a detached entity, silently
            // overwriting another patient's address row (IDOR).
            // If existing.getAddress() was not null the entity is already managed with the
            // correct id — there is no reason to reassign it.
            address.setStreet(dto.address().street());
            address.setNumber(dto.address().number());
            address.setLocation(dto.address().location());
            address.setProvince(dto.address().province());
            existing.setAddress(address);
        } else {
            // address: null in the request → clear the existing address
            existing.setAddress(null);
        }

        return toDTO(patientRepository.save(existing));
    }

    @Override
    @Transactional
    public void delete(Long id) {
        Patient patient = patientRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("No se pudo eliminar el paciente con id: " + id));
        // Eliminar los turnos vinculados antes de borrar el paciente
        // para no violar la FK de appointments.patient_id
        appointmentRepository.deleteAllByPatient_Id(id);
        patientRepository.delete(patient);
    }

    @Override
    @Transactional(readOnly = true)
    public List<PatientDTO> findAll() {
        return patientRepository.findAll().stream().map(this::toDTO).toList();
    }

    // ── Mapping ─────────────────────────────────────────────────────────────

    private PatientDTO toDTO(Patient patient) {
        AddressDTO addressDTO = null;
        if (patient.getAddress() != null) {
            Address a = patient.getAddress();
            addressDTO = new AddressDTO(a.getId(), a.getStreet(), a.getNumber(), a.getLocation(), a.getProvince());
        }
        return new PatientDTO(
                patient.getId(),
                patient.getName(),
                patient.getLastName(),
                patient.getEmail(),
                patient.getCardIdentity(),
                patient.getAdmissionDate(),
                addressDTO
        );
    }

    private Patient toEntity(PatientDTO dto) {
        Patient patient = new Patient();
        // Never copy the id from a DTO used in save() — the id is generated by the DB.
        // update() loads a managed entity instead of calling toEntity(), so id is never needed here.
        patient.setName(dto.name());
        patient.setLastName(dto.lastName());
        patient.setEmail(dto.email());
        patient.setCardIdentity(dto.cardIdentity());
        patient.setAdmissionDate(dto.admissionDate());
        if (dto.address() != null) {
            Address address = new Address();
            // Never copy address.id from the DTO in save() — the DB generates it via IDENTITY.
            // Copying a non-null id would trigger em.merge() on a detached Address, silently
            // overwriting another patient's address record.
            address.setStreet(dto.address().street());
            address.setNumber(dto.address().number());
            address.setLocation(dto.address().location());
            address.setProvince(dto.address().province());
            patient.setAddress(address);
        }
        return patient;
    }
}
